# Generated by Django 6.0.4 on 2026-04-27 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_vacancytranslation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.CharField(blank=True, choices=[('part_time', 'Part time'), ('internship', 'Internship')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('employer_to_student', 'Employer to student'), ('student_to_employer', 'Student to employer')], default='student_to_employer', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('application_submitted', 'Application submitted'), ('status_updated', 'Status updated'), ('new_vacancy', 'New vacancy'), ('interview_scheduled', 'Interview scheduled'), ('review_created', 'Review created')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='portal.application'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('application', 'author', 'review_type'), name='unique_application_author_review_type'),
        ),
        migrations.AddField(
            model_name='vacancysubscription',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.department'),
        ),
        migrations.AddField(
            model_name='vacancysubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
