# Generated by Django 6.0.4 on 2026-04-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_vacancysubscription_review_review_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='portal.vacancy'),
        ),
    ]
