# Generated by Django 6.0.4 on 2026-04-22 19:00

from django.db import migrations, models


def backfill_translation_locations(apps, schema_editor):
    VacancyTranslation = apps.get_model("portal", "VacancyTranslation")
    for translation in VacancyTranslation.objects.select_related("vacancy").all():
        if translation.location:
            continue
        base_location = translation.vacancy.location or ""
        if base_location:
            translation.location = base_location
            translation.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_department_role_created_at_role_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancytranslation',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(backfill_translation_locations, migrations.RunPython.noop),
    ]
