import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const supported = ["en", "de", "ru"] as const;
type Lang = (typeof supported)[number];

const queryLang = new URLSearchParams(window.location.search).get("lang");
const savedLang = localStorage.getItem("lang");
const browserLang = navigator.language?.slice(0, 2);

const detectLang = (): Lang => {
  const candidate = queryLang || savedLang || browserLang || "en";
  return (supported as readonly string[]).includes(candidate) ? (candidate as Lang) : "en";
};

const resources = {
  en: {
    translation: {
      nav: {
        home: "Home",
        vacancies: "Vacancies",
        dashboard: "Dashboard",
        applications: "My Applications",
        admin: "Employer Panel",
        adminShort: "Panel",
        login: "Login",
        register: "Register",
        logout: "Logout",
        profile: "Profile",
        notifications: "Updates",
        calendar: "Calendar",
        reviews: "Reviews",
        tools: "Services"
      },
      common: {
        loading: "Loading...",
        notFound: "Not found",
        loginRequired: "Login required:",
        unexpectedError: "Unexpected error",
        cancel: "Cancel",
        open: "Open",
        status: "Status",
        type: "Type",
        department: "Department",
        role: "Role",
        location: "Location",
        notSpecified: "Not specified",
        from: "from",
        to: "to",
        hoursPerWeek: "hours/week"
      },
      roles: {
        student: "Student",
        employer: "Employer",
        admin: "Administrator"
      },
      languages: {
        en: "English",
        de: "German",
        ru: "Russian"
      },
      status: {
        submitted: "submitted",
        under_review: "under review",
        interview: "interview",
        accepted: "accepted",
        rejected: "rejected",
        active: "active",
        draft: "draft",
        archived: "archived"
      },
      home: {
        pageTitle: "Home",
        heroTitle: "Find campus jobs and internships faster",
        heroSubtitle: "One platform for students, departments, and partner employers.",
        browseVacancies: "Browse vacancies",
        forEmployers: "For employers",
        quickStats: "Quick Stats",
        activeVacancies: "active vacancies",
        studentApplications: "student applications",
        localization: "localization",
        featuredOpportunities: "Featured campus opportunities",
        searchPlaceholder: "Search by role, department, or keyword",
        featuredInternship: "Featured Internship",
        paid: "Paid",
        activeVacanciesSmall: "Active vacancies",
        newUpdates: "New updates",
        new: "new"
      },
      vacancies: {
        title: "Vacancies List",
        searchPlaceholder: "Search by keyword, company, role...",
        department: "Department",
        allDepartments: "All departments",
        type: "Type",
        allTypes: "All types",
        campus: "Campus",
        partTime: "Part-time",
        internship: "Internship",
        open: "Open",
        recommended: "Recommended for you",
        recommendedHint: "Based on your profile and applications."
      },
      vacancyDetails: {
        title: "Vacancy Details",
        invalidId: "Invalid vacancy id",
        vacancyNotFound: "Vacancy not found.",
        mainInfo: "Vacancy information",
        description: "Description",
        department: "Department",
        employer: "Employer",
        employmentType: "Employment type",
        location: "Location",
        workload: "Workload",
        salary: "Salary",
        deadline: "Application deadline",
        responsibilities: "Responsibilities",
        requirements: "Requirements",
        apply: "Apply"
      },
      apply: {
        title: "Apply Form",
        vacancyContext: "Vacancy you are applying to",
        submitTitle: "Submit your application",
        resume: "Resume",
        coverLetter: "Cover letter",
        messageForEmployer: "Message for employer",
        coverLetterPlaceholder: "Write why you fit this role...",
        employerMessagePlaceholder: "Additional details...",
        sendApplication: "Send Application",
        sending: "Sending...",
        invalidId: "Invalid vacancy id."
      },
      dashboard: {
        title: "Profile",
        defaultStudent: "Student",
        email: "Email",
        role: "Role",
        preferredLanguage: "Preferred language",
        quickActions: "Quick Actions",
        browseVacancies: "Browse vacancies",
        viewMyApplications: "View my applications",
        openEmployerPanel: "Open employer panel",
        editProfile: "Edit student profile",
        editEmployerProfile: "Edit employer profile",
        saveProfile: "Save profile",
        savingProfile: "Saving...",
        programPlaceholder: "e.g. Computer Science",
        resumeTitle: "Resume title",
        resumeTitlePlaceholder: "e.g. alex_cv.pdf",
        resumeFile: "Resume file",
        position: "Position",
        positionPlaceholder: "e.g. HR coordinator",
        employerDepartment: "Department",
        employerDepartmentPlaceholder: "e.g. Career Center"
      },
      myApplications: {
        title: "Student Dashboard / My Applications",
        profile: "Profile",
        name: "Name",
        program: "Program",
        year: "Year",
        resume: "Resume",
        noApplications: "No applications yet.",
        myApplications: "My Applications",
        status: "Status",
        studentMessage: "Message for employer",
        coverLetter: "Cover letter",
        employerComment: "Employer comment"
      },
      auth: {
        loginTitle: "Login",
        loginSubtitle: "Sign in to apply for vacancies and track application statuses.",
        username: "Username",
        loginIdentifier: "Username or email",
        roleStudent: "Student",
        roleEmployer: "Employer",
        usernamePlaceholder: "Enter your username",
        loginIdentifierPlaceholder: "Enter username or email",
        password: "Password",
        passwordPlaceholder: "Enter your password",
        signingIn: "Signing in...",
        loginButton: "Login",
        createAccount: "Create account",
        registerTitle: "Register",
        registerSubtitle: "Create a student account to apply for campus vacancies.",
        studentHint: "Student accounts can be created directly. Employer accounts are issued by administration.",
        employerHint: "Employer accounts are issued by the university administration.",
        preferredLanguage: "Preferred language",
        firstName: "First name",
        lastName: "Last name",
        organizationName: "Organization name",
        organizationNamePlaceholder: "Department or company name",
        confirmPassword: "Confirm password",
        passwordsMismatch: "Passwords do not match.",
        creating: "Creating...",
        backToLogin: "Back to login",
        loggingOut: "Logging out..."
      },
      admin: {
        title: "Employer Vacancy Management",
        actions: "Actions",
        selectVacancy: "Vacancies",
        showApplications: "Show applications",
        selectedVacancy: "Selected vacancy",
        createVacancy: "Create Vacancy",
        editVacancy: "Edit Vacancy",
        applicationsByVacancy: "Applications by Vacancy",
        noApplications: "No applications for this vacancy yet.",
        openApplication: "Open details",
        hideApplication: "Hide details",
        applicationsCount: "{{count}} applications",
        setStatus: "Set",
        loadToEditor: "Load to editor",
        createModeTitle: "Create vacancy",
        editModeTitle: "Edit vacancy",
        editing: "Editing",
        departmentId: "Department",
        departmentName: "Department",
        departmentPlaceholder: "Enter any department name",
        departmentRequired: "Department is required.",
        type: "Type",
        location: "Location",
        workloadHours: "Workload (hours/week)",
        salaryFrom: "Salary from",
        salaryTo: "Salary to",
        applicationDeadline: "Application deadline",
        status: "Status",
        titleField: "Title",
        descriptionField: "Description",
        responsibilitiesField: "Responsibilities",
        requirementsField: "Requirements",
        baseLanguage: "(main)",
        optionalLanguage: "(optional)",
        addTranslation: "Add {{lang}} localization",
        saveChanges: "Save changes",
        saving: "Saving...",
        vacancyCreated: "Vacancy created",
        vacancyUpdated: "Vacancy updated",
        updatedApplications: "Updated {{count}} applications",
        applicant: "Applicant",
        contact: "Contact",
        resume: "Resume",
        openResume: "Open resume",
        noResume: "No resume attached",
        studentMessage: "Student message",
        coverLetter: "Cover letter",
        employerComment: "Employer comment",
        commentPlaceholder: "Add a comment for the candidate...",
        saveApplication: "Save application",
        applicationUpdated: "Application updated",
        scheduleInterview: "Schedule interview",
        interviewDate: "Date and time",
        interviewDateRequired: "Interview date is required.",
        interviewNotes: "Notes",
        employerReview: "Employer review",
        rating: "Rating",
        reviewComment: "Review comment",
        saveReview: "Save review"
      },
      footer: {
        product: "Student jobs and internships",
        contact: "Contact",
        email: "example@gmail.com"
      },
      pages: {
        notFound: "Page not found"
      }
    }
  },
  de: {
    translation: {
      nav: {
        home: "Startseite",
        vacancies: "Stellenangebote",
        dashboard: "Dashboard",
        applications: "Meine Bewerbungen",
        admin: "Arbeitgeberbereich",
        adminShort: "Panel",
        login: "Anmelden",
        register: "Registrieren",
        logout: "Abmelden",
        profile: "Profil",
        notifications: "Updates",
        calendar: "Kalender",
        reviews: "Bewertungen",
        tools: "Services"
      },
      common: {
        loading: "Wird geladen...",
        notFound: "Nicht gefunden",
        loginRequired: "Anmeldung erforderlich:",
        unexpectedError: "Unerwarteter Fehler",
        cancel: "Abbrechen",
        open: "Öffnen",
        status: "Status",
        type: "Typ",
        department: "Abteilung",
        role: "Rolle",
        location: "Standort",
        notSpecified: "Nicht angegeben",
        from: "ab",
        to: "bis",
        hoursPerWeek: "Stunden/Woche"
      },
      roles: {
        student: "Student",
        employer: "Arbeitgeber",
        admin: "Administrator"
      },
      languages: {
        en: "Englisch",
        de: "Deutsch",
        ru: "Russisch"
      },
      status: {
        submitted: "eingereicht",
        under_review: "in Prüfung",
        interview: "Interview",
        accepted: "angenommen",
        rejected: "abgelehnt",
        active: "aktiv",
        draft: "Entwurf",
        archived: "archiviert"
      },
      home: {
        pageTitle: "Startseite",
        heroTitle: "Finde Campus-Jobs und Praktika schneller",
        heroSubtitle: "Eine Plattform für Studierende, Fachbereiche und Partnerarbeitgeber.",
        browseVacancies: "Stellen ansehen",
        forEmployers: "Für Arbeitgeber",
        quickStats: "Kurzstatistik",
        activeVacancies: "aktive Stellen",
        studentApplications: "studentische Bewerbungen",
        localization: "Lokalisierung",
        featuredOpportunities: "Ausgewählte Campus-Angebote",
        searchPlaceholder: "Suche nach Rolle, Abteilung oder Stichwort",
        featuredInternship: "Empfohlenes Praktikum",
        paid: "Bezahlt",
        activeVacanciesSmall: "Aktive Stellen",
        newUpdates: "Neue Updates",
        new: "neu"
      },
      vacancies: {
        title: "Stellenliste",
        searchPlaceholder: "Suche nach Stichwort, Unternehmen, Rolle...",
        department: "Abteilung",
        allDepartments: "Alle Abteilungen",
        type: "Typ",
        allTypes: "Alle Typen",
        campus: "Campus",
        partTime: "Teilzeit",
        internship: "Praktikum",
        open: "Öffnen",
        recommended: "Empfohlen für dich",
        recommendedHint: "Basierend auf deinem Profil und deinen Bewerbungen."
      },
      vacancyDetails: {
        title: "Stellendetails",
        invalidId: "Ungültige Stellen-ID",
        vacancyNotFound: "Stelle nicht gefunden.",
        mainInfo: "Informationen zur Stelle",
        description: "Beschreibung",
        department: "Abteilung",
        employer: "Arbeitgeber",
        employmentType: "Beschäftigungsart",
        location: "Standort",
        workload: "Arbeitszeit",
        salary: "Gehalt",
        deadline: "Bewerbungsfrist",
        responsibilities: "Aufgaben",
        requirements: "Anforderungen",
        apply: "Bewerben"
      },
      apply: {
        title: "Bewerbungsformular",
        vacancyContext: "Stelle, auf die du dich bewirbst",
        submitTitle: "Bewerbung senden",
        resume: "Lebenslauf",
        coverLetter: "Anschreiben",
        messageForEmployer: "Nachricht an Arbeitgeber",
        coverLetterPlaceholder: "Schreibe, warum du zu dieser Stelle passt...",
        employerMessagePlaceholder: "Weitere Details...",
        sendApplication: "Bewerbung senden",
        sending: "Wird gesendet...",
        invalidId: "Ungültige Stellen-ID."
      },
      dashboard: {
        title: "Profil",
        defaultStudent: "Student",
        email: "E-Mail",
        role: "Rolle",
        preferredLanguage: "Bevorzugte Sprache",
        quickActions: "Schnellaktionen",
        browseVacancies: "Stellen ansehen",
        viewMyApplications: "Meine Bewerbungen ansehen",
        openEmployerPanel: "Arbeitgeberbereich öffnen",
        editProfile: "Studentenprofil bearbeiten",
        editEmployerProfile: "Arbeitgeberprofil bearbeiten",
        saveProfile: "Profil speichern",
        savingProfile: "Speichern...",
        programPlaceholder: "z. B. Informatik",
        resumeTitle: "Lebenslauf-Titel",
        resumeTitlePlaceholder: "z. B. alex_cv.pdf",
        resumeFile: "Lebenslauf-Datei",
        position: "Position",
        positionPlaceholder: "z. B. HR-Koordinator",
        employerDepartment: "Abteilung",
        employerDepartmentPlaceholder: "z. B. Career Center"
      },
      myApplications: {
        title: "Studenten-Dashboard / Meine Bewerbungen",
        profile: "Profil",
        name: "Name",
        program: "Studiengang",
        year: "Studienjahr",
        resume: "Lebenslauf",
        noApplications: "Noch keine Bewerbungen.",
        myApplications: "Meine Bewerbungen",
        status: "Status",
        studentMessage: "Nachricht an Arbeitgeber",
        coverLetter: "Anschreiben",
        employerComment: "Kommentar des Arbeitgebers"
      },
      auth: {
        loginTitle: "Anmelden",
        loginSubtitle: "Melde dich an, um dich zu bewerben und Status zu verfolgen.",
        username: "Benutzername",
        loginIdentifier: "Benutzername oder E-Mail",
        roleStudent: "Student",
        roleEmployer: "Arbeitgeber",
        usernamePlaceholder: "Benutzernamen eingeben",
        loginIdentifierPlaceholder: "Benutzername oder E-Mail eingeben",
        password: "Passwort",
        passwordPlaceholder: "Passwort eingeben",
        signingIn: "Anmeldung...",
        loginButton: "Anmelden",
        createAccount: "Konto erstellen",
        registerTitle: "Registrieren",
        registerSubtitle: "Erstelle ein Studentenkonto, um dich auf Campus-Stellen zu bewerben.",
        studentHint: "Studentenkonten können direkt erstellt werden. Arbeitgeberkonten werden von der Verwaltung vergeben.",
        employerHint: "Arbeitgeberkonten werden von der Universitätsverwaltung vergeben.",
        preferredLanguage: "Bevorzugte Sprache",
        firstName: "Vorname",
        lastName: "Nachname",
        organizationName: "Organisationsname",
        organizationNamePlaceholder: "Abteilung oder Unternehmen",
        confirmPassword: "Passwort bestätigen",
        passwordsMismatch: "Passwörter stimmen nicht überein.",
        creating: "Wird erstellt...",
        backToLogin: "Zur Anmeldung",
        loggingOut: "Abmeldung..."
      },
      admin: {
        title: "Stellenverwaltung für Arbeitgeber",
        actions: "Aktionen",
        selectVacancy: "Stellen",
        showApplications: "Bewerbungen anzeigen",
        selectedVacancy: "Ausgewählte Stelle",
        createVacancy: "Stelle erstellen",
        editVacancy: "Stelle bearbeiten",
        applicationsByVacancy: "Bewerbungen nach Stelle",
        noApplications: "Für diese Stelle gibt es noch keine Bewerbungen.",
        openApplication: "Details öffnen",
        hideApplication: "Details ausblenden",
        applicationsCount: "{{count}} Bewerbungen",
        setStatus: "Setzen",
        loadToEditor: "In den Editor laden",
        createModeTitle: "Stelle erstellen",
        editModeTitle: "Stelle bearbeiten",
        editing: "Bearbeitung",
        departmentId: "Abteilung",
        departmentName: "Abteilung",
        departmentPlaceholder: "Beliebigen Abteilungsnamen eingeben",
        departmentRequired: "Abteilung ist erforderlich.",
        type: "Typ",
        location: "Standort",
        workloadHours: "Arbeitszeit (Stunden/Woche)",
        salaryFrom: "Gehalt von",
        salaryTo: "Gehalt bis",
        applicationDeadline: "Bewerbungsfrist",
        status: "Status",
        titleField: "Titel",
        descriptionField: "Beschreibung",
        responsibilitiesField: "Aufgaben",
        requirementsField: "Anforderungen",
        baseLanguage: "(Hauptversion)",
        optionalLanguage: "(optional)",
        addTranslation: "{{lang}}-Lokalisierung hinzufügen",
        saveChanges: "Änderungen speichern",
        saving: "Speichern...",
        vacancyCreated: "Stelle erstellt",
        vacancyUpdated: "Stelle aktualisiert",
        updatedApplications: "{{count}} Bewerbungen aktualisiert",
        applicant: "Bewerber",
        contact: "Kontakt",
        resume: "Lebenslauf",
        openResume: "Lebenslauf öffnen",
        noResume: "Kein Lebenslauf angehängt",
        studentMessage: "Nachricht des Studierenden",
        coverLetter: "Anschreiben",
        employerComment: "Kommentar des Arbeitgebers",
        commentPlaceholder: "Kommentar für den Kandidaten hinzufügen...",
        saveApplication: "Bewerbung speichern",
        applicationUpdated: "Bewerbung aktualisiert",
        scheduleInterview: "Interview planen",
        interviewDate: "Datum und Uhrzeit",
        interviewDateRequired: "Interviewdatum ist erforderlich.",
        interviewNotes: "Notizen",
        employerReview: "Arbeitgeberbewertung",
        rating: "Bewertung",
        reviewComment: "Bewertungskommentar",
        saveReview: "Bewertung speichern"
      },
      footer: {
        product: "Studentenjobs und Praktika",
        contact: "Kontakt",
        email: "example@gmail.com"
      },
      pages: {
        notFound: "Seite nicht gefunden"
      }
    }
  },
  ru: {
    translation: {
      nav: {
        home: "Главная",
        vacancies: "Вакансии",
        dashboard: "Кабинет",
        applications: "Мои заявки",
        admin: "Панель работодателя",
        adminShort: "Панель",
        login: "Вход",
        register: "Регистрация",
        logout: "Выход",
        profile: "Профиль",
        notifications: "Уведомления",
        calendar: "Календарь",
        reviews: "Отзывы",
        tools: "Сервисы"
      },
      common: {
        loading: "Загрузка...",
        notFound: "Не найдено",
        loginRequired: "Требуется вход:",
        unexpectedError: "Непредвиденная ошибка",
        cancel: "Отмена",
        open: "Открыть",
        status: "Статус",
        type: "Тип",
        department: "Подразделение",
        role: "Роль",
        location: "Локация",
        notSpecified: "Не указано",
        from: "от",
        to: "до",
        hoursPerWeek: "часов/неделю"
      },
      roles: {
        student: "Студент",
        employer: "Работодатель",
        admin: "Администратор"
      },
      languages: {
        en: "Английский",
        de: "Немецкий",
        ru: "Русский"
      },
      status: {
        submitted: "отправлено",
        under_review: "на рассмотрении",
        interview: "интервью",
        accepted: "принято",
        rejected: "отклонено",
        active: "активна",
        draft: "черновик",
        archived: "в архиве"
      },
      home: {
        pageTitle: "Главная",
        heroTitle: "Находите работу и стажировки в университете быстрее",
        heroSubtitle: "Единая платформа для студентов, подразделений и партнерских работодателей.",
        browseVacancies: "Смотреть вакансии",
        forEmployers: "Для работодателей",
        quickStats: "Быстрая статистика",
        activeVacancies: "активных вакансий",
        studentApplications: "студенческих откликов",
        localization: "локализация",
        featuredOpportunities: "Рекомендуемые предложения",
        searchPlaceholder: "Поиск по роли, подразделению или ключевому слову",
        featuredInternship: "Рекомендуемая стажировка",
        paid: "Оплачиваемая",
        activeVacanciesSmall: "Активные вакансии",
        newUpdates: "Новые обновления",
        new: "новое"
      },
      vacancies: {
        title: "Список вакансий",
        searchPlaceholder: "Поиск по ключевому слову, компании, роли...",
        department: "Подразделение",
        allDepartments: "Все подразделения",
        type: "Тип",
        allTypes: "Все типы",
        campus: "Кампус",
        partTime: "Частичная занятость",
        internship: "Стажировка",
        open: "Открыть",
        recommended: "Рекомендовано для вас",
        recommendedHint: "На основе профиля и ваших заявок."
      },
      vacancyDetails: {
        title: "Детали вакансии",
        invalidId: "Некорректный ID вакансии",
        vacancyNotFound: "Вакансия не найдена.",
        mainInfo: "Информация о вакансии",
        description: "Описание",
        department: "Подразделение",
        employer: "Работодатель",
        employmentType: "Тип занятости",
        location: "Локация",
        workload: "Занятость",
        salary: "Оплата",
        deadline: "Дедлайн подачи",
        responsibilities: "Обязанности",
        requirements: "Требования",
        apply: "Откликнуться"
      },
      apply: {
        title: "Форма отклика",
        vacancyContext: "Вакансия, на которую вы откликаетесь",
        submitTitle: "Отправьте заявку",
        resume: "Резюме",
        coverLetter: "Сопроводительное письмо",
        messageForEmployer: "Сообщение работодателю",
        coverLetterPlaceholder: "Напишите, почему вы подходите на эту роль...",
        employerMessagePlaceholder: "Дополнительные детали...",
        sendApplication: "Отправить отклик",
        sending: "Отправка...",
        invalidId: "Некорректный ID вакансии."
      },
      dashboard: {
        title: "Профиль",
        defaultStudent: "Студент",
        email: "Email",
        role: "Роль",
        preferredLanguage: "Предпочитаемый язык",
        quickActions: "Быстрые действия",
        browseVacancies: "Смотреть вакансии",
        viewMyApplications: "Мои заявки",
        openEmployerPanel: "Открыть панель работодателя",
        editProfile: "Редактировать профиль студента",
        editEmployerProfile: "Редактировать профиль работодателя",
        saveProfile: "Сохранить профиль",
        savingProfile: "Сохранение...",
        programPlaceholder: "например, Компьютерные науки",
        resumeTitle: "Название резюме",
        resumeTitlePlaceholder: "например, alex_cv.pdf",
        resumeFile: "Файл резюме",
        position: "Должность",
        positionPlaceholder: "например, HR-координатор",
        employerDepartment: "Подразделение",
        employerDepartmentPlaceholder: "например, Центр карьеры"
      },
      myApplications: {
        title: "Кабинет студента / Мои заявки",
        profile: "Профиль",
        name: "Имя",
        program: "Программа",
        year: "Курс",
        resume: "Резюме",
        noApplications: "Пока нет заявок.",
        myApplications: "Мои заявки",
        status: "Статус",
        studentMessage: "Сообщение работодателю",
        coverLetter: "Сопроводительное письмо",
        employerComment: "Комментарий работодателя"
      },
      auth: {
        loginTitle: "Вход",
        loginSubtitle: "Войдите, чтобы откликаться на вакансии и отслеживать статусы заявок.",
        username: "Логин",
        loginIdentifier: "Логин или email",
        roleStudent: "Студент",
        roleEmployer: "Работодатель",
        usernamePlaceholder: "Введите логин",
        loginIdentifierPlaceholder: "Введите логин или email",
        password: "Пароль",
        passwordPlaceholder: "Введите пароль",
        signingIn: "Вход...",
        loginButton: "Войти",
        createAccount: "Создать аккаунт",
        registerTitle: "Регистрация",
        registerSubtitle: "Создайте студенческий аккаунт, чтобы откликаться на вакансии университета.",
        studentHint: "Студенческий аккаунт можно создать сразу. Аккаунты работодателей выдаёт администрация.",
        employerHint: "Аккаунты работодателей выдает администрация университета.",
        preferredLanguage: "Предпочитаемый язык",
        firstName: "Имя",
        lastName: "Фамилия",
        organizationName: "Название организации",
        organizationNamePlaceholder: "Подразделение или компания",
        confirmPassword: "Подтвердите пароль",
        passwordsMismatch: "Пароли не совпадают.",
        creating: "Создание...",
        backToLogin: "Назад ко входу",
        loggingOut: "Выход..."
      },
      admin: {
        title: "Управление вакансиями работодателя",
        actions: "Действия",
        selectVacancy: "Вакансии",
        showApplications: "Показать отклики",
        selectedVacancy: "Выбранная вакансия",
        createVacancy: "Создать вакансию",
        editVacancy: "Редактировать вакансию",
        applicationsByVacancy: "Отклики по вакансии",
        noApplications: "По этой вакансии пока нет откликов.",
        openApplication: "Открыть детали",
        hideApplication: "Скрыть детали",
        applicationsCount: "{{count}} откликов",
        setStatus: "Установить",
        loadToEditor: "Загрузить в редактор",
        createModeTitle: "Создать вакансию",
        editModeTitle: "Редактировать вакансию",
        editing: "Редактирование",
        departmentId: "Подразделение",
        departmentName: "Подразделение",
        departmentPlaceholder: "Введите любое название подразделения",
        departmentRequired: "Подразделение обязательно.",
        type: "Тип",
        location: "Локация",
        workloadHours: "Занятость (часов/неделю)",
        salaryFrom: "Оплата от",
        salaryTo: "Оплата до",
        applicationDeadline: "Дедлайн подачи",
        status: "Статус",
        titleField: "Название",
        descriptionField: "Описание",
        responsibilitiesField: "Обязанности",
        requirementsField: "Требования",
        baseLanguage: "(основная версия)",
        optionalLanguage: "(необязательно)",
        addTranslation: "Добавить локализацию {{lang}}",
        saveChanges: "Сохранить изменения",
        saving: "Сохранение...",
        vacancyCreated: "Вакансия создана",
        vacancyUpdated: "Вакансия обновлена",
        updatedApplications: "Обновлено откликов: {{count}}",
        applicant: "Кандидат",
        contact: "Контакт",
        resume: "Резюме",
        openResume: "Открыть резюме",
        noResume: "Резюме не прикреплено",
        studentMessage: "Сообщение студента",
        coverLetter: "Сопроводительное письмо",
        employerComment: "Комментарий работодателя",
        commentPlaceholder: "Добавьте комментарий для кандидата...",
        saveApplication: "Сохранить отклик",
        applicationUpdated: "Отклик обновлен",
        scheduleInterview: "Назначить собеседование",
        interviewDate: "Дата и время",
        interviewDateRequired: "Дата собеседования обязательна.",
        interviewNotes: "Заметки",
        employerReview: "Отзыв работодателя",
        rating: "Оценка",
        reviewComment: "Комментарий к отзыву",
        saveReview: "Сохранить отзыв"
      },
      footer: {
        product: "Работа и стажировки для студентов",
        contact: "Контакты",
        email: "example@gmail.com"
      },
      pages: {
        notFound: "Страница не найдена"
      }
    }
  }
};

i18n.use(initReactI18next).init({
  resources,
  lng: detectLang(),
  fallbackLng: "en",
  interpolation: { escapeValue: false }
});

export default i18n;
